name        : icon-naming-utils
version     : 0.8.90
release     : 2
source      :
    - http://tango.freedesktop.org/releases/icon-naming-utils-0.8.90.tar.bz2 : b1378679df4485b4459f609a3304238b3e92d91e43744c47b70abbe690d883d5
license     :
    - GPLv2+
summary     : Icon theme naming script
builddeps   :
    - perl-xmlsimple
    - perl-xml-saxbase
    - perl-xml-namespacesupport
description : |
    The icon-naming-utils package contains a script used for maintaining backwards compatibility with current desktop icon themes, while migrating to the names specified in the Icon Naming Specification.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
